/* Marvin Redpost 어휘 단어장 (공개용)
   - 단어는 Marvin Redpost: Kidnapped at Birth에 나오는 낱말을 빈도순으로 추출
   - 예문(en)은 저작권 문제가 없도록 전부 새로 창작한 문장 (원작 문장 아님)
   - 한글 뜻/해석은 직접 작성
   형식: {d:Day, w:단어, ko:뜻, en:영어예문, k:예문 해석} */
window.VOCAB = [
{d:1,w:"asked",ko:"물었다",en:"She asked me a difficult question.",k:"그녀는 나에게 어려운 질문을 했다."},
{d:1,w:"king",ko:"왕",en:"The king ruled the whole country.",k:"왕은 나라 전체를 다스렸다."},
{d:1,w:"blood",ko:"피",en:"There was blood on his knee.",k:"그의 무릎에 피가 났다."},
{d:1,w:"woman",ko:"여자",en:"The woman is reading a book.",k:"그 여자는 책을 읽고 있다."},
{d:1,w:"baby",ko:"아기",en:"The baby is sleeping now.",k:"아기는 지금 자고 있다."},
{d:1,w:"mother",ko:"엄마, 어머니",en:"My mother cooks dinner every night.",k:"우리 엄마는 매일 밤 저녁을 요리한다."},
{d:1,w:"number",ko:"숫자|번호",en:"Please write your phone number here.",k:"여기에 전화번호를 적어 주세요."},
{d:1,w:"hair",ko:"머리카락",en:"She has long black hair.",k:"그녀는 길고 검은 머리카락을 가졌다."},
{d:1,w:"boy",ko:"소년",en:"The boy is playing soccer.",k:"그 소년은 축구를 하고 있다."},
{d:1,w:"took",ko:"가져갔다, 데려갔다",en:"He took my pencil without asking.",k:"그는 묻지도 않고 내 연필을 가져갔다."},
{d:1,w:"shampoo",ko:"샴푸",en:"I wash my hair with shampoo.",k:"나는 샴푸로 머리를 감는다."},
{d:1,w:"test",ko:"검사|시험",en:"We have a math test tomorrow.",k:"우리는 내일 수학 시험이 있다."},
{d:1,w:"day",ko:"날, 하루",en:"It was a warm and sunny day.",k:"따뜻하고 화창한 날이었다."},
{d:1,w:"really",ko:"정말로",en:"I really like this song.",k:"나는 이 노래가 정말 좋다."},
{d:1,w:"thought",ko:"생각했다|생각",en:"I thought about it all night.",k:"나는 밤새 그것에 대해 생각했다."},
{d:1,w:"son",ko:"아들",en:"Their son is ten years old.",k:"그들의 아들은 열 살이다."},
{d:1,w:"dead",ko:"죽은",en:"The old tree is dead.",k:"그 오래된 나무는 죽었다."},
{d:1,w:"hospital",ko:"병원",en:"My uncle works at a hospital.",k:"우리 삼촌은 병원에서 일한다."},
{d:1,w:"kidnapper",ko:"유괴범",en:"The police caught the kidnapper.",k:"경찰이 유괴범을 잡았다."},
{d:1,w:"told",ko:"말했다",en:"She told me the truth.",k:"그녀는 나에게 진실을 말했다."},
{d:1,w:"want",ko:"원하다",en:"I want a glass of water.",k:"나는 물 한 잔을 원한다."},
{d:1,w:"man",ko:"남자",en:"The man is wearing a hat.",k:"그 남자는 모자를 쓰고 있다."},
{d:1,w:"call",ko:"부르다|전화하다",en:"Please call me tonight.",k:"오늘 밤 나에게 전화해 줘."},
{d:1,w:"time",ko:"시간|때",en:"What time is it now?",k:"지금 몇 시니?"},
{d:1,w:"parent",ko:"부모",en:"Every parent loves their child.",k:"모든 부모는 자기 아이를 사랑한다."},
{d:1,w:"laughed",ko:"웃었다",en:"We laughed at the funny movie.",k:"우리는 그 웃긴 영화를 보고 웃었다."},
{d:1,w:"know",ko:"알다",en:"I know the answer.",k:"나는 답을 안다."},
{d:1,w:"walked",ko:"걸었다",en:"We walked to school together.",k:"우리는 함께 학교까지 걸어갔다."},
{d:1,w:"door",ko:"문",en:"Please close the door.",k:"문을 닫아 주세요."},
{d:1,w:"take",ko:"가져가다, 잡다",en:"Take an umbrella with you.",k:"우산을 가져가."},
{d:1,w:"new",ko:"새로운",en:"I bought a new bag.",k:"나는 새 가방을 샀다."},
{d:1,w:"mean",ko:"의미하다|못된, 심술궂은",en:"What does this word mean?",k:"이 단어는 무슨 뜻이니?"},
{d:1,w:"smiled",ko:"미소지었다",en:"She smiled at her friend.",k:"그녀는 친구에게 미소지었다."},
{d:1,w:"name",ko:"이름",en:"My name is Jenny.",k:"내 이름은 제니야."},
{d:1,w:"sorry",ko:"미안한",en:"I'm sorry for being late.",k:"늦어서 미안해."},
{d:1,w:"father",ko:"아빠, 아버지",en:"My father drives a blue car.",k:"우리 아빠는 파란 차를 운전한다."},
{d:1,w:"lady",ko:"숙녀, 여성",en:"The old lady fed the birds.",k:"그 나이 든 여성은 새들에게 먹이를 주었다."},
{d:1,w:"nasty",ko:"못된, 고약한",en:"He said something nasty to me.",k:"그는 나에게 고약한 말을 했다."},
{d:1,w:"negative",ko:"음성의|부정적인",en:"The test result was negative.",k:"검사 결과는 음성이었다."},
{d:1,w:"house",ko:"집",en:"They live in a big house.",k:"그들은 큰 집에 산다."},
{d:2,w:"kidnapped",ko:"유괴된",en:"In the story, the prince was kidnapped.",k:"그 이야기에서 왕자는 유괴되었다."},
{d:2,w:"lost",ko:"잃어버린, 길을 잃은",en:"I lost my keys this morning.",k:"나는 오늘 아침 열쇠를 잃어버렸다."},
{d:2,w:"born",ko:"태어난",en:"She was born in spring.",k:"그녀는 봄에 태어났다."},
{d:2,w:"anything",ko:"아무것, 무엇이든",en:"I didn't eat anything today.",k:"나는 오늘 아무것도 먹지 않았다."},
{d:2,w:"way",ko:"길|방법",en:"Can you show me the way?",k:"나에게 길을 알려줄 수 있니?"},
{d:2,w:"redhaired",ko:"빨간 머리의",en:"A redhaired girl sat next to me.",k:"빨간 머리 소녀가 내 옆에 앉았다."},
{d:2,w:"earring",ko:"귀걸이",en:"She lost one gold earring.",k:"그녀는 금 귀걸이 한 짝을 잃어버렸다."},
{d:2,w:"royal",ko:"왕의, 왕실의",en:"The royal family lives in a palace.",k:"왕실 가족은 궁전에 산다."},
{d:2,w:"eye",ko:"눈",en:"He has bright blue eyes.",k:"그는 밝은 파란 눈을 가졌다."},
{d:2,w:"gave",ko:"주었다",en:"She gave me a present.",k:"그녀는 나에게 선물을 주었다."},
{d:2,w:"white",ko:"하얀",en:"Snow is white and cold.",k:"눈은 하얗고 차갑다."},
{d:2,w:"home",ko:"집",en:"I go home after school.",k:"나는 방과 후에 집에 간다."},
{d:2,w:"room",ko:"방",en:"My room is small but cozy.",k:"내 방은 작지만 아늑하다."},
{d:2,w:"called",ko:"불렀다, ~라고 불리는",en:"My teacher called my name.",k:"선생님이 내 이름을 불렀다."},
{d:2,w:"knew",ko:"알았다",en:"I knew the answer right away.",k:"나는 즉시 답을 알았다."},
{d:2,w:"probably",ko:"아마도",en:"It will probably rain today.",k:"오늘 아마 비가 올 것이다."},
{d:2,w:"lot",ko:"많음 (a lot 많이)",en:"There are a lot of people here.",k:"여기에 사람이 많다."},
{d:2,w:"everyone",ko:"모두",en:"Everyone was happy at the party.",k:"파티에서 모두가 행복했다."},
{d:2,w:"something",ko:"어떤 것",en:"I want to tell you something.",k:"너에게 뭔가 말하고 싶어."},
{d:2,w:"year",ko:"년, 해",en:"We moved here last year.",k:"우리는 작년에 여기로 이사 왔다."},
{d:2,w:"around",ko:"주위에",en:"We sat around the table.",k:"우리는 탁자 주위에 앉았다."},
{d:2,w:"dog",ko:"개",en:"My dog likes to run.",k:"우리 개는 뛰는 것을 좋아한다."},
{d:2,w:"think",ko:"생각하다",en:"I think you are right.",k:"나는 네가 맞다고 생각해."},
{d:2,w:"second",ko:"두 번째|초",en:"He came in second in the race.",k:"그는 경주에서 2등으로 들어왔다."},
{d:2,w:"sure",ko:"확실한",en:"Are you sure about that?",k:"그거 확실하니?"},
{d:2,w:"front",ko:"앞",en:"She sat in the front row.",k:"그녀는 앞줄에 앉았다."},
{d:2,w:"please",ko:"제발|기쁘게 하다",en:"Please help me with this.",k:"이것 좀 도와주세요."},
{d:2,w:"exactly",ko:"정확히",en:"That's exactly what I meant.",k:"그게 바로 내가 말한 거야."},
{d:2,w:"stopped",ko:"멈췄다",en:"The bus stopped at the corner.",k:"버스가 모퉁이에서 멈췄다."},
{d:2,w:"thank",ko:"감사하다",en:"I want to thank you for your help.",k:"도와줘서 고맙다는 말을 하고 싶어."},
{d:2,w:"phone",ko:"전화",en:"My phone is out of battery.",k:"내 전화기는 배터리가 다 됐다."},
{d:2,w:"end",ko:"끝|끝나다",en:"We waited until the end.",k:"우리는 끝까지 기다렸다."},
{d:2,w:"first",ko:"첫 번째, 처음",en:"She was the first to arrive.",k:"그녀가 가장 먼저 도착했다."},
{d:2,w:"lefthanded",ko:"왼손잡이의",en:"My brother is left-handed.",k:"우리 형은 왼손잡이다."},
{d:2,w:"picked",ko:"골랐다, 집었다",en:"I picked a red apple.",k:"나는 빨간 사과를 골랐다."},
{d:2,w:"nine",ko:"아홉, 9",en:"The class starts at nine.",k:"수업은 9시에 시작한다."},
{d:2,w:"blue",ko:"파란",en:"The sky is clear and blue.",k:"하늘이 맑고 파랗다."},
{d:2,w:"afraid",ko:"두려운, 무서운",en:"I'm afraid of the dark.",k:"나는 어둠이 무섭다."},
{d:2,w:"stupid",ko:"멍청한",en:"It was a stupid mistake.",k:"그것은 멍청한 실수였다."},
{d:2,w:"remember",ko:"기억하다",en:"I can't remember his name.",k:"나는 그의 이름이 기억나지 않는다."},
{d:3,w:"family",ko:"가족",en:"My family eats dinner together.",k:"우리 가족은 함께 저녁을 먹는다."},
{d:3,w:"brown",ko:"갈색",en:"She wore a brown coat.",k:"그녀는 갈색 코트를 입었다."},
{d:3,w:"right",ko:"오른쪽|옳은",en:"Turn right at the corner.",k:"모퉁이에서 오른쪽으로 도세요."},
{d:3,w:"car",ko:"자동차",en:"Their car is very fast.",k:"그들의 자동차는 매우 빠르다."},
{d:3,w:"tell",ko:"말하다",en:"Don't tell anyone my secret.",k:"내 비밀을 아무에게도 말하지 마."},
{d:3,w:"mad",ko:"화난",en:"My mom was mad at me.",k:"엄마는 나에게 화가 났다."},
{d:3,w:"homework",ko:"숙제",en:"I finished my homework early.",k:"나는 숙제를 일찍 끝냈다."},
{d:3,w:"next",ko:"다음",en:"The next bus comes soon.",k:"다음 버스가 곧 온다."},
{d:3,w:"desk",ko:"책상",en:"My books are on the desk.",k:"내 책들은 책상 위에 있다."},
{d:3,w:"television",ko:"텔레비전",en:"We watched television after dinner.",k:"우리는 저녁 후에 텔레비전을 봤다."},
{d:3,w:"away",ko:"떨어져, 멀리",en:"The school is far away.",k:"학교는 멀리 떨어져 있다."},
{d:3,w:"later",ko:"나중에",en:"I'll call you later.",k:"나중에 전화할게."},
{d:3,w:"watched",ko:"지켜봤다",en:"We watched the game together.",k:"우리는 함께 그 경기를 봤다."},
{d:3,w:"hand",ko:"손",en:"Raise your hand to answer.",k:"대답하려면 손을 드세요."},
{d:3,w:"elevator",ko:"엘리베이터",en:"We took the elevator to the fifth floor.",k:"우리는 엘리베이터를 타고 5층에 갔다."},
{d:3,w:"coat",ko:"코트, 외투",en:"Wear a warm coat outside.",k:"밖에서는 따뜻한 코트를 입어라."},
{d:3,w:"line",ko:"줄, 선",en:"Draw a straight line here.",k:"여기에 직선을 그으세요."},
{d:3,w:"slip",ko:"미끄러지다|쪽지",en:"Be careful not to slip on the ice.",k:"얼음에서 미끄러지지 않게 조심해."},
{d:3,w:"paper",ko:"종이",en:"I need a sheet of paper.",k:"나는 종이 한 장이 필요하다."},
{d:3,w:"type",ko:"유형, 종류|타자치다",en:"What type of music do you like?",k:"어떤 종류의 음악을 좋아하니?"},
{d:3,w:"read",ko:"읽다",en:"I read a book every night.",k:"나는 매일 밤 책을 읽는다."},
{d:3,w:"class",ko:"반, 수업",en:"Our class has thirty students.",k:"우리 반에는 서른 명의 학생이 있다."},
{d:3,w:"write",ko:"쓰다",en:"Please write your name here.",k:"여기에 이름을 쓰세요."},
{d:3,w:"returned",ko:"돌아왔다",en:"He returned home late.",k:"그는 집에 늦게 돌아왔다."},
{d:3,w:"wrote",ko:"썼다",en:"She wrote a letter to her friend.",k:"그녀는 친구에게 편지를 썼다."},
{d:3,w:"ran",ko:"달렸다",en:"We ran to catch the bus.",k:"우리는 버스를 잡으려고 달렸다."},
{d:3,w:"outside",ko:"밖에",en:"The children are playing outside.",k:"아이들이 밖에서 놀고 있다."},
{d:3,w:"play",ko:"놀다|경기하다",en:"Let's play in the park.",k:"공원에서 놀자."},
{d:3,w:"best",ko:"최고의",en:"She is my best friend.",k:"그녀는 나의 가장 친한 친구다."},
{d:3,w:"friend",ko:"친구",en:"I have a new friend.",k:"나는 새 친구가 생겼다."},
{d:3,w:"good",ko:"좋은",en:"This is a good idea.",k:"이것은 좋은 생각이다."},
{d:3,w:"wrong",ko:"틀린, 잘못된",en:"You have the wrong answer.",k:"너는 답이 틀렸다."},
{d:3,w:"thing",ko:"것, 물건",en:"I have many things to do.",k:"나는 할 일이 많다."},
{d:3,w:"queen",ko:"여왕",en:"The queen wore a golden crown.",k:"여왕은 금관을 썼다."},
{d:3,w:"moment",ko:"순간",en:"Wait a moment, please.",k:"잠깐만 기다려 주세요."},
{d:3,w:"maybe",ko:"아마",en:"Maybe we can meet tomorrow.",k:"아마 우리는 내일 만날 수 있어."},
{d:3,w:"never",ko:"결코 ~않다",en:"I never lie to my friends.",k:"나는 친구에게 결코 거짓말하지 않는다."},
{d:3,w:"make",ko:"만들다",en:"Let's make a cake together.",k:"함께 케이크를 만들자."},
{d:3,w:"shrugged",ko:"어깨를 으쓱했다",en:"He just shrugged and said nothing.",k:"그는 그냥 어깨를 으쓱하고 아무 말도 하지 않았다."},
{d:3,w:"buy",ko:"사다",en:"I want to buy new shoes.",k:"나는 새 신발을 사고 싶다."},
{d:4,w:"see",ko:"보다",en:"I can see the mountain from here.",k:"여기서 산이 보인다."},
{d:4,w:"people",ko:"사람들",en:"Many people came to the show.",k:"많은 사람들이 공연에 왔다."},
{d:4,w:"watch",ko:"보다, 지켜보다|시계",en:"He got a new watch for his birthday.",k:"그는 생일에 새 시계를 받았다."},
{d:4,w:"sounded",ko:"들렸다, ~처럼 들렸다",en:"The plan sounded good to me.",k:"그 계획은 나에게 좋게 들렸다."},
{d:4,w:"muttered",ko:"중얼거렸다",en:"He muttered something under his breath.",k:"그는 낮은 목소리로 뭔가 중얼거렸다."},
{d:4,w:"every",ko:"모든",en:"I brush my teeth every morning.",k:"나는 매일 아침 이를 닦는다."},
{d:4,w:"stuck",ko:"갇힌, 꼼짝 못하는",en:"The car was stuck in the mud.",k:"자동차가 진흙에 빠져 꼼짝 못했다."},
{d:4,w:"grandparent",ko:"조부모",en:"My grandparents live in the country.",k:"우리 조부모님은 시골에 사신다."},
{d:4,w:"still",ko:"여전히",en:"It is still raining outside.",k:"밖에는 여전히 비가 온다."},
{d:4,w:"happen",ko:"일어나다, 생기다",en:"What will happen next?",k:"다음에 무슨 일이 일어날까?"},
{d:4,w:"turned",ko:"돌았다, 돌렸다",en:"She turned and looked at me.",k:"그녀는 돌아서서 나를 봤다."},
{d:4,w:"different",ko:"다른",en:"We have different opinions.",k:"우리는 다른 의견을 가지고 있다."},
{d:4,w:"spoke",ko:"말했다",en:"He spoke slowly and clearly.",k:"그는 천천히 또렷하게 말했다."},
{d:4,w:"need",ko:"필요하다",en:"I need your help now.",k:"나는 지금 네 도움이 필요해."},
{d:4,w:"shut",ko:"닫다",en:"Please shut the window.",k:"창문을 닫아 주세요."},
{d:4,w:"true",ko:"진실인, 사실인",en:"Is the story true?",k:"그 이야기가 사실이니?"},
{d:4,w:"head",ko:"머리",en:"He hit his head on the door.",k:"그는 문에 머리를 부딪쳤다."},
{d:4,w:"felt",ko:"느꼈다",en:"I felt happy after the trip.",k:"나는 여행 후에 행복함을 느꼈다."},
{d:4,w:"ever",ko:"언제나|한 번이라도",en:"Have you ever seen a whale?",k:"고래를 본 적이 있니?"},
{d:4,w:"real",ko:"진짜의",en:"Is this a real diamond?",k:"이것은 진짜 다이아몬드니?"},
{d:4,w:"shook",ko:"흔들었다",en:"She shook her head slowly.",k:"그녀는 천천히 고개를 흔들었다."},
{d:4,w:"quarter",ko:"4분의 1|25센트",en:"I ate a quarter of the pizza.",k:"나는 피자의 4분의 1을 먹었다."},
{d:4,w:"welcome",ko:"환영하다",en:"Welcome to our school!",k:"우리 학교에 온 걸 환영해!"},
{d:4,w:"tomorrow",ko:"내일",en:"See you tomorrow morning.",k:"내일 아침에 봐."},
{d:4,w:"dinner",ko:"저녁식사",en:"Dinner is ready now.",k:"저녁 식사가 준비됐다."},
{d:4,w:"shouted",ko:"소리쳤다",en:"He shouted for help.",k:"그는 도와달라고 소리쳤다."},
{d:4,w:"polo",ko:"폴로|(마르코)폴로 놀이",en:"We played Marco Polo in the pool.",k:"우리는 수영장에서 마르코 폴로 놀이를 했다."},
{d:4,w:"tube",ko:"관, 튜브",en:"Squeeze the toothpaste from the tube.",k:"튜브에서 치약을 짜라."},
{d:4,w:"report",ko:"보고서|보고하다",en:"I wrote a report about animals.",k:"나는 동물에 관한 보고서를 썼다."},
{d:4,w:"lucky",ko:"운 좋은",en:"You are lucky to win.",k:"이기다니 너는 운이 좋아."},
{d:4,w:"fast",ko:"빠른, 빨리",en:"He runs very fast.",k:"그는 매우 빨리 달린다."},
{d:4,w:"current",ko:"현재의|흐름",en:"The current temperature is very high.",k:"현재 기온이 매우 높다."},
{d:4,w:"ago",ko:"~전에",en:"We met two years ago.",k:"우리는 2년 전에 만났다."},
{d:4,w:"old",ko:"늙은, 오래된",en:"This is a very old house.",k:"이것은 아주 오래된 집이다."},
{d:4,w:"unless",ko:"~하지 않는 한",en:"You'll be late unless you hurry.",k:"서두르지 않으면 늦을 거야."},
{d:4,w:"hope",ko:"바라다, 희망하다|희망",en:"I hope you feel better soon.",k:"네가 곧 나아지길 바라."},
{d:4,w:"week",ko:"주, 일주일",en:"I have piano lessons every week.",k:"나는 매주 피아노 수업이 있다."},
{d:4,w:"lived",ko:"살았다",en:"They lived in Paris for a year.",k:"그들은 파리에서 일 년 동안 살았다."},
{d:4,w:"school",ko:"학교",en:"Our school is near the park.",k:"우리 학교는 공원 근처에 있다."},
{d:4,w:"keep",ko:"유지하다, 계속하다",en:"Keep your room clean.",k:"방을 깨끗하게 유지해라."},
{d:5,w:"exclaimed",ko:"외쳤다",en:"\"We won!\" she exclaimed happily.",k:"\"우리가 이겼어!\" 그녀가 기쁘게 외쳤다."},
{d:5,w:"explained",ko:"설명했다",en:"The teacher explained the rules.",k:"선생님이 규칙을 설명했다."},
{d:5,w:"wait",ko:"기다리다",en:"Wait for me at the gate.",k:"정문에서 나를 기다려."},
{d:5,w:"left",ko:"왼쪽|떠났다",en:"Turn left at the bank.",k:"은행에서 왼쪽으로 도세요."},
{d:5,w:"handed",ko:"건네주었다",en:"She handed me a cup of tea.",k:"그녀는 나에게 차 한 잔을 건네주었다."},
{d:5,w:"adopted",ko:"입양된",en:"They adopted a small puppy.",k:"그들은 작은 강아지를 입양했다."},
{d:5,w:"found",ko:"찾았다, 발견했다",en:"I found my lost ring.",k:"나는 잃어버린 반지를 찾았다."},
{d:5,w:"servant",ko:"하인",en:"The king had many servants.",k:"왕에게는 많은 하인이 있었다."},
{d:5,w:"much",ko:"많은",en:"I don't have much money.",k:"나는 돈이 많지 않다."},
{d:5,w:"except",ko:"~을 제외하고",en:"Everyone came except Tom.",k:"톰을 제외하고 모두 왔다."},
{d:5,w:"behind",ko:"~뒤에",en:"The cat is hiding behind the sofa.",k:"고양이가 소파 뒤에 숨어 있다."},
{d:5,w:"glass",ko:"유리|유리잔",en:"Be careful, the glass is broken.",k:"조심해, 유리가 깨졌어."},
{d:5,w:"morning",ko:"아침",en:"I drink milk every morning.",k:"나는 매일 아침 우유를 마신다."},
{d:5,w:"watching",ko:"보고 있는",en:"They are watching a movie.",k:"그들은 영화를 보고 있다."},
{d:5,w:"dad",ko:"아빠",en:"My dad reads the newspaper.",k:"우리 아빠는 신문을 읽는다."},
{d:5,w:"happened",ko:"일어났다",en:"What happened to your arm?",k:"네 팔에 무슨 일이 있었니?"},
{d:5,w:"pretty",ko:"예쁜|꽤",en:"She has a pretty smile.",k:"그녀는 예쁜 미소를 가졌다."},
{d:5,w:"heard",ko:"들었다",en:"I heard a strange noise.",k:"나는 이상한 소리를 들었다."},
{d:5,w:"gold",ko:"금",en:"The ring is made of gold.",k:"그 반지는 금으로 만들어졌다."},
{d:5,w:"face",ko:"얼굴",en:"Wash your face before bed.",k:"자기 전에 얼굴을 씻어라."},
{d:5,w:"someone",ko:"누군가",en:"Someone is knocking at the door.",k:"누군가 문을 두드리고 있다."},
{d:5,w:"big",ko:"큰",en:"They have a big garden.",k:"그들은 큰 정원을 가지고 있다."},
{d:5,w:"meant",ko:"의미했다",en:"I didn't know what she meant.",k:"나는 그녀가 무엇을 의미했는지 몰랐다."},
{d:5,w:"answer",ko:"대답|대답하다",en:"Please answer my question.",k:"내 질문에 대답해 주세요."},
{d:5,w:"kid",ko:"아이",en:"The kids are playing outside.",k:"아이들이 밖에서 놀고 있다."},
{d:5,w:"dungeon",ko:"지하 감옥",en:"The prisoner was kept in a dark dungeon.",k:"죄수는 어두운 지하 감옥에 갇혀 있었다."},
{d:5,w:"arm",ko:"팔",en:"He broke his arm playing soccer.",k:"그는 축구를 하다 팔이 부러졌다."},
{d:5,w:"everybody",ko:"모두",en:"Everybody likes summer vacation.",k:"모두가 여름 방학을 좋아한다."},
{d:5,w:"hid",ko:"숨었다, 숨겼다",en:"She hid the gift under the bed.",k:"그녀는 선물을 침대 밑에 숨겼다."},
{d:5,w:"mistake",ko:"실수",en:"Everyone makes mistakes sometimes.",k:"누구나 가끔 실수를 한다."},
{d:5,w:"mind",ko:"마음|신경 쓰다",en:"Never mind, it's not important.",k:"신경 쓰지 마, 중요하지 않아."},
{d:5,w:"goodbye",ko:"안녕 (작별 인사)",en:"She waved goodbye to us.",k:"그녀는 우리에게 손을 흔들며 작별 인사를 했다."},
{d:5,w:"thousand",ko:"천, 1000",en:"A thousand people came to the fair.",k:"천 명의 사람들이 축제에 왔다."},
{d:5,w:"ice",ko:"얼음",en:"I put ice in my drink.",k:"나는 음료에 얼음을 넣었다."},
{d:5,w:"breath",ko:"숨, 호흡",en:"Take a deep breath and relax.",k:"깊게 숨을 쉬고 긴장을 풀어라."},
{d:5,w:"almost",ko:"거의",en:"We are almost there.",k:"우리는 거의 다 왔다."},
{d:5,w:"nice",ko:"멋진, 친절한",en:"He is a very nice person.",k:"그는 아주 친절한 사람이다."},
{d:5,w:"made",ko:"만들었다",en:"She made a paper airplane.",k:"그녀는 종이비행기를 만들었다."},
{d:5,w:"crying",ko:"우는",en:"The baby is crying loudly.",k:"아기가 크게 울고 있다."},
{d:5,w:"across",ko:"~을 가로질러, 건너서",en:"We walked across the bridge.",k:"우리는 다리를 건너 걸어갔다."},
{d:6,w:"followed",ko:"따라갔다",en:"The puppy followed me home.",k:"강아지가 나를 따라 집까지 왔다."},
{d:6,w:"million",ko:"백만",en:"The city has a million people.",k:"그 도시에는 백만 명이 산다."},
{d:6,w:"yellow",ko:"노란",en:"The sunflower is bright yellow.",k:"해바라기는 밝은 노란색이다."},
{d:6,w:"remembered",ko:"기억했다",en:"She remembered my birthday.",k:"그녀는 내 생일을 기억했다."},
{d:6,w:"world",ko:"세계",en:"I want to travel around the world.",k:"나는 세계를 여행하고 싶다."},
{d:6,w:"birth",ko:"출생, 탄생",en:"We celebrated the birth of the baby.",k:"우리는 아기의 탄생을 축하했다."},
{d:6,w:"pencil",ko:"연필",en:"Can I borrow your pencil?",k:"네 연필을 빌려도 될까?"},
{d:6,w:"north",ko:"북쪽",en:"The wind is blowing from the north.",k:"바람이 북쪽에서 불고 있다."},
{d:6,w:"neater",ko:"더 깔끔한",en:"Your handwriting is neater than mine.",k:"네 글씨가 내 것보다 더 깔끔하다."},
{d:6,w:"writing",ko:"쓰기|글씨",en:"I am writing a letter now.",k:"나는 지금 편지를 쓰고 있다."},
{d:6,w:"seat",ko:"자리, 좌석",en:"Is this seat taken?",k:"이 자리 주인 있나요?"},
{d:6,w:"children",ko:"아이들",en:"The children sang a song.",k:"아이들이 노래를 불렀다."},
{d:6,w:"finished",ko:"끝냈다, 마쳤다",en:"I finished my dinner quickly.",k:"나는 저녁을 빨리 끝냈다."},
{d:6,w:"rang",ko:"(전화·종이) 울렸다",en:"The phone rang three times.",k:"전화가 세 번 울렸다."},
{d:6,w:"full",ko:"가득 찬",en:"The glass is full of water.",k:"유리잔이 물로 가득 차 있다."},
{d:6,w:"candy",ko:"사탕",en:"The children love candy.",k:"아이들은 사탕을 좋아한다."},
{d:6,w:"fight",ko:"싸움|싸우다",en:"The two boys had a fight.",k:"두 소년이 싸웠다."},
{d:6,w:"thinking",ko:"생각하는",en:"I am thinking about my future.",k:"나는 내 미래에 대해 생각하고 있다."},
{d:6,w:"believe",ko:"믿다",en:"I believe you can do it.",k:"나는 네가 할 수 있다고 믿어."},
{d:6,w:"wanted",ko:"원했다",en:"She wanted a puppy for her birthday.",k:"그녀는 생일에 강아지를 원했다."},
{d:6,w:"quickly",ko:"빨리",en:"He ate his lunch quickly.",k:"그는 점심을 빨리 먹었다."},
{d:6,w:"part",ko:"부분",en:"This is the best part of the movie.",k:"이것이 영화에서 가장 좋은 부분이다."},
{d:6,w:"hide",ko:"숨다, 숨기다",en:"Let's hide behind the tree.",k:"나무 뒤에 숨자."},
{d:6,w:"better",ko:"더 좋은",en:"This book is better than that one.",k:"이 책이 저 책보다 더 좋다."},
{d:6,w:"place",ko:"장소, 곳",en:"This is a quiet place to study.",k:"여기는 공부하기 조용한 곳이다."},
{d:6,w:"bet",ko:"내기하다|장담하다",en:"I bet you can't catch me.",k:"네가 나를 못 잡을 거라고 장담해."},
{d:6,w:"whispered",ko:"속삭였다",en:"She whispered a secret in my ear.",k:"그녀는 내 귀에 비밀을 속삭였다."},
{d:6,w:"might",ko:"~일지도 모른다",en:"It might snow tonight.",k:"오늘 밤 눈이 올지도 모른다."},
{d:6,w:"live",ko:"살다",en:"I live near the school.",k:"나는 학교 근처에 산다."},
{d:6,w:"castle",ko:"성",en:"The old castle stands on a hill.",k:"오래된 성이 언덕 위에 서 있다."},
{d:6,w:"hundred",ko:"백, 100",en:"The book has a hundred pages.",k:"그 책은 백 페이지이다."},
{d:6,w:"bed",ko:"침대",en:"I go to bed at nine.",k:"나는 9시에 잠자리에 든다."},
{d:6,w:"give",ko:"주다",en:"Give me your hand.",k:"손을 이리 줘."},
{d:6,w:"luck",ko:"운",en:"Good luck on your test!",k:"시험 잘 봐! (행운을 빌어)"},
{d:6,w:"kill",ko:"죽이다",en:"The hero fought to kill the dragon.",k:"영웅은 용을 죽이려고 싸웠다."},
{d:6,w:"fence",ko:"울타리",en:"The dog jumped over the fence.",k:"개가 울타리를 뛰어넘었다."},
{d:6,w:"gate",ko:"문, 대문",en:"Please close the front gate.",k:"앞 대문을 닫아 주세요."},
{d:6,w:"eleven",ko:"열하나, 11",en:"There are eleven players on the team.",k:"그 팀에는 열한 명의 선수가 있다."},
{d:6,w:"coming",ko:"오는",en:"Winter is coming soon.",k:"겨울이 곧 온다."},
{d:6,w:"clean",ko:"깨끗한|청소하다",en:"I clean my room on Sundays.",k:"나는 일요일마다 방을 청소한다."},
{d:7,w:"help",ko:"돕다|도움",en:"Can you help me carry this?",k:"이거 옮기는 것 좀 도와줄래?"},
{d:7,w:"idea",ko:"생각, 아이디어",en:"That's a great idea!",k:"그거 좋은 생각이야!"},
{d:7,w:"supposed",ko:"~하기로 되어 있는",en:"We are supposed to meet at noon.",k:"우리는 정오에 만나기로 되어 있다."},
{d:7,w:"wondered",ko:"궁금해했다",en:"I wondered where she went.",k:"나는 그녀가 어디로 갔는지 궁금했다."},
{d:7,w:"yelled",ko:"소리 질렀다",en:"The coach yelled at the players.",k:"코치가 선수들에게 소리를 질렀다."},
{d:7,w:"lizard",ko:"도마뱀",en:"A small lizard ran across the rock.",k:"작은 도마뱀이 바위를 가로질러 달렸다."},
{d:7,w:"tongue",ko:"혀",en:"The dog stuck out its tongue.",k:"개가 혀를 내밀었다."},
{d:7,w:"seemed",ko:"~인 것 같았다",en:"He seemed tired after the trip.",k:"그는 여행 후에 피곤해 보였다."},
{d:7,w:"single",ko:"단 하나의",en:"Not a single star was in the sky.",k:"하늘에 별이 단 하나도 없었다."},
{d:7,w:"talk",ko:"말하다, 이야기하다",en:"Let's talk about the plan.",k:"그 계획에 대해 이야기하자."},
{d:7,w:"alive",ko:"살아 있는",en:"The old fish is still alive.",k:"그 늙은 물고기는 아직 살아 있다."},
{d:7,w:"accent",ko:"억양|악센트",en:"She speaks with a British accent.",k:"그녀는 영국식 억양으로 말한다."},
{d:7,w:"throne",ko:"왕좌",en:"The king sat on his throne.",k:"왕이 왕좌에 앉았다."},
{d:7,w:"kingdom",ko:"왕국",en:"The kingdom was rich and peaceful.",k:"그 왕국은 부유하고 평화로웠다."},
{d:7,w:"await",ko:"기다리다",en:"Great adventures await you.",k:"멋진 모험이 너를 기다린다."},
{d:7,w:"waiting",ko:"기다리는",en:"I am waiting for the bus.",k:"나는 버스를 기다리고 있다."},
{d:7,w:"grandmother",ko:"할머니",en:"My grandmother bakes delicious bread.",k:"우리 할머니는 맛있는 빵을 구우신다."},
{d:7,w:"saying",ko:"말하는",en:"What are you saying?",k:"무슨 말을 하는 거니?"},
{d:7,w:"seen",ko:"봤다, 본 적 있다",en:"I have seen that movie twice.",k:"나는 그 영화를 두 번 봤다."},
{d:7,w:"throw",ko:"던지다",en:"Throw the ball to me.",k:"나에게 공을 던져."},
{d:7,w:"sat",ko:"앉았다",en:"We sat on the grass.",k:"우리는 잔디에 앉았다."},
{d:7,w:"liked",ko:"좋아했다",en:"She liked the gift very much.",k:"그녀는 그 선물을 매우 좋아했다."},
{d:7,w:"stood",ko:"서 있었다",en:"He stood by the window.",k:"그는 창가에 서 있었다."},
{d:7,w:"kind",ko:"친절한|종류",en:"She is kind to everyone.",k:"그녀는 모두에게 친절하다."},
{d:7,w:"black",ko:"검은",en:"The cat has black fur.",k:"그 고양이는 검은 털을 가졌다."},
{d:7,w:"excuse",ko:"용서하다, 변명|(excuse me) 실례합니다",en:"Excuse me, where is the station?",k:"실례합니다, 역이 어디인가요?"},
{d:7,w:"taking",ko:"가져가는",en:"He is taking pictures of the flowers.",k:"그는 꽃 사진을 찍고 있다."},
{d:7,w:"died",ko:"죽었다",en:"The plant died without water.",k:"그 식물은 물 없이 죽었다."},
{d:7,w:"extra",ko:"여분의, 추가의",en:"I brought an extra pencil.",k:"나는 여분의 연필을 가져왔다."},
{d:7,w:"happy",ko:"행복한",en:"The happy dog wagged its tail.",k:"행복한 개가 꼬리를 흔들었다."},
{d:7,w:"held",ko:"잡았다, 들고 있었다",en:"She held the baby gently.",k:"그녀는 아기를 부드럽게 안았다."},
{d:7,w:"pulled",ko:"당겼다",en:"He pulled the door open.",k:"그는 문을 당겨서 열었다."},
{d:7,w:"pocket",ko:"주머니",en:"I put the coin in my pocket.",k:"나는 동전을 주머니에 넣었다."},
{d:7,w:"cracked",ko:"금이 간, 깨진",en:"The old cup is cracked.",k:"그 오래된 컵은 금이 갔다."},
{d:7,w:"allowance",ko:"용돈",en:"I save part of my allowance.",k:"나는 용돈의 일부를 저축한다."},
{d:7,w:"eat",ko:"먹다",en:"We eat lunch at noon.",k:"우리는 정오에 점심을 먹는다."},
{d:7,w:"deep",ko:"깊은",en:"The river is very deep here.",k:"이곳의 강은 매우 깊다."},
{d:7,w:"answered",ko:"대답했다",en:"She answered the phone quickly.",k:"그녀는 전화를 빨리 받았다."},
{d:7,w:"thirty",ko:"서른, 30",en:"There are thirty days in this month.",k:"이번 달은 30일이다."},
{d:7,w:"talking",ko:"말하는",en:"They are talking on the phone.",k:"그들은 전화로 이야기하고 있다."},
{d:8,w:"taco",ko:"타코",en:"We ate tacos for lunch.",k:"우리는 점심으로 타코를 먹었다."},
{d:8,w:"hear",ko:"듣다",en:"I can hear the birds singing.",k:"새들이 노래하는 소리가 들린다."},
{d:8,w:"quite",ko:"꽤, 상당히",en:"The test was quite easy.",k:"시험이 꽤 쉬웠다."},
{d:8,w:"kept",ko:"유지했다, 계속했다",en:"She kept the room warm.",k:"그녀는 방을 따뜻하게 유지했다."},
{d:8,w:"former",ko:"이전의, 예전의",en:"He is a former teacher.",k:"그는 예전 선생님이다."},
{d:8,w:"replied",ko:"대답했다",en:"\"Yes,\" he replied politely.",k:"\"네,\" 그가 공손하게 대답했다."},
{d:8,w:"sound",ko:"소리|들리다",en:"I heard a loud sound.",k:"나는 큰 소리를 들었다."},
{d:8,w:"agreed",ko:"동의했다",en:"We all agreed on the plan.",k:"우리는 모두 그 계획에 동의했다."},
{d:8,w:"even",ko:"~조차, 심지어",en:"Even a child can do this.",k:"심지어 아이도 이것을 할 수 있다."},
{d:8,w:"miss",ko:"그리워하다|놓치다",en:"I miss my old friends.",k:"나는 옛 친구들이 그립다."},
{d:8,w:"yet",ko:"아직",en:"I haven't finished yet.",k:"나는 아직 끝내지 못했다."},
{d:8,w:"saw",ko:"봤다",en:"I saw a rabbit in the garden.",k:"나는 정원에서 토끼를 봤다."},
{d:8,w:"matter",ko:"문제|중요하다",en:"What's the matter with you?",k:"너 무슨 일이야?"},
{d:8,w:"game",ko:"게임, 경기",en:"We won the soccer game.",k:"우리는 축구 경기에서 이겼다."},
{d:8,w:"lobby",ko:"로비",en:"Let's meet in the hotel lobby.",k:"호텔 로비에서 만나자."},
{d:8,w:"dragging",ko:"끌고 가는",en:"He was dragging a heavy bag.",k:"그는 무거운 가방을 끌고 가고 있었다."},
{d:8,w:"stepped",ko:"걸음을 내디뎠다",en:"She stepped onto the stage.",k:"그녀는 무대 위로 걸음을 내디뎠다."},
{d:8,w:"noticed",ko:"알아차렸다",en:"I noticed a mistake in my essay.",k:"나는 내 글에서 실수를 알아차렸다."},
{d:8,w:"delighted",ko:"아주 기뻐하는",en:"She was delighted with her gift.",k:"그녀는 선물을 받고 아주 기뻐했다."},
{d:8,w:"acquaintance",ko:"아는 사람, 지인",en:"He is just an acquaintance, not a friend.",k:"그는 친구가 아니라 그냥 아는 사람이다."},
{d:8,w:"find",ko:"찾다",en:"I can't find my glasses.",k:"나는 안경을 찾을 수 없다."},
{d:8,w:"odd",ko:"이상한|홀수의",en:"One, three, and five are odd numbers.",k:"1, 3, 5는 홀수이다."},
{d:8,w:"waited",ko:"기다렸다",en:"We waited for an hour.",k:"우리는 한 시간 동안 기다렸다."},
{d:8,w:"special",ko:"특별한",en:"Today is a special day.",k:"오늘은 특별한 날이다."},
{d:8,w:"while",ko:"~하는 동안",en:"She sang while she cooked.",k:"그녀는 요리하는 동안 노래했다."},
{d:8,w:"needle",ko:"바늘",en:"Be careful with the sharp needle.",k:"날카로운 바늘 조심해."},
{d:8,w:"weird",ko:"이상한",en:"I had a weird dream last night.",k:"나는 어젯밤 이상한 꿈을 꿨다."},
{d:8,w:"fifty",ko:"쉰, 50",en:"There are fifty stars on the flag.",k:"그 깃발에는 별이 50개 있다."},
{d:8,w:"eight",ko:"여덟, 8",en:"I wake up at eight o'clock.",k:"나는 8시에 일어난다."},
{d:8,w:"glad",ko:"기쁜",en:"I'm glad to see you.",k:"너를 만나서 기뻐."},
{d:8,w:"skate",ko:"스케이트를 타다",en:"We skate on the frozen lake.",k:"우리는 얼어붙은 호수에서 스케이트를 탄다."}
];
